database:
  type: "postgres"
  host: "localhost"
  port: 9090
  username: "nestjs_server"
  password: "somereallysecurepassword.com"
  database_name: "holidays"
settings:
  # Try request to the API to verify data is identical after sent response.
  # In case it is not, data will be merged and another response must return current data.
  # This can only be made after the response is sent to the caller.
  try_source_after_success: false
  # Set amount of skips to not send the request to try request to the API
  # In case it is zero, then every request will additionally to database call the API
  # Defaults to udnefined/0
  # try_source_after_success_skips: 0
  # Set on which day of the week to do try request to the API
  # Overwrites previous setting (skips)
  # 0 - Monday, 1 - Tuesday, ... , 6 - Sunday 
  # 0 - January, 1 - February, ... , 11 - December
  # Default is undefined/empty, meaning its out of scope
  # try_source_after_success_on_days: [0,1,2,3,4,5,6]
  # try_source_after_success_on_months: []
  # try_source_after_success_on_years: []
  # Sets if try request must be made every day/month/year
  # Collects date of last synchronization (API) from the database table.
  # If ..._on_days setting is provided, first day of sync will follow ..._on_days setting.
  # Default is undefined/false.
  try_source_after_success_every_day: false
  try_source_after_success_every_month: false
  try_source_after_success_every_year: false
  # Allows to send the request to the API, before it is found that data in the database is missing 
  # OR if it is checked for potential update
  hotload: true